top = '..'

def build(bld):
    bld.program(target='../unit-tests',
                name='unit-tests',
                source=bld.path.ant_glob('**/*.cpp'),
                use='PSync',
                install_path=None)
