# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

top = '..'

def build(bld):
    bld.program(
        target=f'{top}/unit-tests',
        name='unit-tests',
        source=bld.path.ant_glob('**/*.cpp'),
        use='BOOST_TESTS PSync',
        install_path=None)
